---

- name: Check if npm is installed
  command: 'npm --version > /dev/null 2>&1'
  register: npm_check
  ignore_errors: True

- name: Install npm
  apt: name=npm
  when: npm_check|failed

- name: Get ping-statsd-agent from Github
  git: repo=https://github.com/garo/ping-statsd-agent.git dest=/opt/ping-statsd-agent

- name: Build it with npm
  command: npm install chdir=/opt/ping-statsd-agent

- name: Configure hosts to be pinged
  template: src=/opt/ping-statsd-agent/hosts.json dest=/opt/ping-statsd-agent/hosts.json

