---
- hosts: all
  tasks:
      
    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present
      
    - name: Add InfluxDB repository
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

    - name: Install InfluxDB packages
      apt: name=influxdb state=present

    - name: Modify InfluxDB hostname
      replace:
        dest=/etc/influxdb/influxdb.conf
        regexp='hostname = "localhost"'
        replace='hostname = "{{ ansible_hostname }}"'
        backup=yes

    - name: Start the InfluxDB service
      service: name=influxdb state=restarted enabled=yes

    - name: Pause for InfluxDB service
      pause: seconds=3
      
    - name: Create sample database
      command: /usr/bin/influx -execute 'CREATE DATABASE sample_database'
      ignore_errors: yes

    - name: Load some test data into sample database
      uri:
        url: http://localhost:8086/write?db=sample_database
        method: POST
        body: "random_ints,host=server_{{ 10 | random }} value={{ 100 | random }}"
        status_code: 204
      with_sequence: start=1 end=20

    - name: Add repository for Grafana
      apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present

    - name: Add repo key for Grafana
      apt_key: url=https://packagecloud.io/gpg.key state=present

    - name: Add Grafana
      apt: name=grafana update_cache=yes 

    - name: Start the grafana service
      service: name=grafana-server state=restarted enabled=yes

- hosts: all
  roles: 
       - { role: telegraf }
  