---

- name: sshd
  hosts: all
  gather_facts: False
  tasks:
    - name: Wait for sshd to be running
      local_action: "wait_for host={{ inventory_hostname }} delay=0 port=22
        timeout=90 state=started"

- name: statsd
  hosts: statsd
  user: '{{ ssh_user }}'
  sudo: true
  vars:
    ssh_user: root
  roles:
    - { role: dmichel1.statsd }
