---
galaxy_info:
  author: Drew Michel
  description: Statsd - Simple daemon for easy stats aggregation
  company: Drewl
  license: MIT
  min_ansible_version: 1.3
  platforms:
  - name: EL
    versions:
    - 6
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - squeeze
    - wheezy
  categories:
  - monitoring
dependencies: []
